[package]
edition = "2021"
name = "family-computer"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.5.6"
bytemuck = {version = "1.14.0", features = ["derive"]}
cfg-if = "1.0.0"
dyn-clone = "1.0.16"
glyphon = "0.3.0"
pollster = "0.3.0"
rand = "0.8.5"
strum = {version = "0.25.0", features = ["derive"]}
wgpu = "0.16.3"
winit = {version = "0.29.4", features = ["rwh_05"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = {version = "0.3", features = [
  "Document",
  "Window",
  "Element",
]}
wgpu = {version = "0.18", features = ["webgl"]}
