[tasks.build-x86_64.mac]
args = ["build", "--release", "--target=x86_64-apple-darwin"]
command = "cargo"

[tasks.build-aarch64.mac]
args = ["build", "--release", "--target=aarch64-apple-darwin"]
command = "cargo"

[tasks.make-universal-release-folder.mac]
args = ["-p", "target/universal-apple/darwin/release"]
command = "mkdir"

[tasks.lipo-universal.mac]
args = [
  "target/x86_64-apple-darwin/release/family-computer",
  "target/aarch64-apple-darwin/release/family-computer",
  "-create",
  "-output",
  "target/universal-apple-darwin/release/family-computer",
]
command = "lipo"
dependencies = ["build-x86_64", "build-aarch64", "make-universal-release-folder"]

[tasks.write-info-plist.mac]
dependencies = ["make-universal-release-folder"]
script = "echo \"$INFO_PLIST_CONTENT\" >target/universal-apple-darwin/release/Info.plist"

[tasks.write-info-plist.mac.env]
INFO_PLIST_CONTENT = '''
{
   CFBundleName = family-computer;
   CFBundleDisplayName = "Family Computer";
   CFBundleIdentifier = "com.natbudin.family-computer";
   CFBundleVersion = "${CARGO_MAKE_PROJECT_VERSION}";
   CFBundleShortVersionString = "${CARGO_MAKE_PROJECT_VERSION}";
   CFBundleInfoDictionaryVersion = "6.0";
   CFBundlePackageType = APPL;
   CFBundleExecutable = family-computer;
   CFBundleIconFile = "Family Computer.icns";
}
'''

[tasks.build-icon.mac]
script = [
  "rm -rf target/universal-apple-darwin/release/Family\\ Computer.iconset",
  "mkdir target/universal-apple-darwin/release/Family\\ Computer.iconset",
  "sips -z 16 16     mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_16x16.png",
  "sips -z 32 32     mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_16x16@2x.png",
  "sips -z 32 32     mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_32x32.png",
  "sips -z 64 64     mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_32x32@2x.png",
  "sips -z 128 128   mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_128x128.png",
  "sips -z 256 256   mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_128x128@2x.png",
  "sips -z 256 256   mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_256x256.png",
  "sips -z 512 512   mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_256x256@2x.png",
  "sips -z 512 512   mos6502.png --out target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_512x512.png",
  "cp mos6502.png target/universal-apple-darwin/release/Family\\ Computer.iconset/icon_512x512@2x.png",
  "iconutil -c icns target/universal-apple-darwin/release/Family\\ Computer.iconset",
  "rm -rf target/universal-apple-darwin/release/Family\\ Computer.iconset",
]

[tasks.build-package.mac]
dependencies = ["lipo-universal", "write-info-plist", "build-icon"]
script = [
  "rm -rf target/universal-apple-darwin/release/Family\\ Computer.app",
  "mkdir -p target/universal-apple-darwin/release/Family\\ Computer.app/Contents/MacOS",
  "mkdir -p target/universal-apple-darwin/release/Family\\ Computer.app/Contents/Resources",
  "mv target/universal-apple-darwin/release/Info.plist target/universal-apple-darwin/release/Family\\ Computer.app/Contents/",
  "mv target/universal-apple-darwin/release/family-computer target/universal-apple-darwin/release/Family\\ Computer.app/Contents/MacOS/",
  "mv target/universal-apple-darwin/release/Family\\ Computer.icns target/universal-apple-darwin/release/Family\\ Computer.app/Contents/Resources/",
  "codesign -s 'Developer ID Application: Nathaniel Budin (V2W3RME3KS)' target/universal-apple-darwin/release/Family\\ Computer.app/",
]

[tasks.build.linux]
args = ["build", "--release"]
command = "cargo"
